export enum RouteNames {
  HomeScreen = "HomeScreen",
  About = "About",
  DrawerNavigation = "DrawerNavigation",
  SCANQR = "SCANQR",
  Login = "Login",
  Register = "Register",
  OTP = "OTP",
  LicenseDetails = "LicenseDetails",
  NotificationList = "NotificationList",
  License = "License",
  UserList = "UserList",
  UserDetails = "UserDetails",
  Parts = "Parts",
  Products_sub_category = "Products_sub_category",
  Products_category_master = "Products_category_master",
  IO_serial_number = "IO_serial_number",
  IPC_service_tag = "IPC_service_tag",
  Lens_info = "Lens_info",
  Comp_lens_serial = "Comp_lens_serial",
  UserProfile = "UserProfile",
}
